### ISSUE TITLE
why not include docker-compose file?

### ISSUE THREAD

**Issue by jf---** [gramaziokohler/ros_docker#1]
why not provide docker-compose.yaml in the `README.md` as integral part of the repo?

I realize this repo is more of a dependency to other repos, perhaps providing a cross-reference is relevant? That goes visa-versa, IMO it could be more explicit that `compas_fab` is using these docker files ( perhaps linking as a `submodule` isn't a bad idea?

**Comment by gonzalocasas** [comment]
We do. The docker-compose.yml files are linked in the [docs of compas_fab](https://gramaziokohler.github.io/compas_fab/latest/backends/ros.html) and also [part of its repo](https://github.com/gramaziokohler/compas_fab/tree/master/docs/backends/files).

And the `Dockerfiles`s for all those are on a different repo: https://github.com/gramaziokohler/ros_docker

**Comment by jf---** [comment]
Yikes, sorry I missed that -- that said, docs aren't a very orthodox location for `docker-compose` files... 

What about providing a `README.md` that points the reader of your project  [compas_fab/backends/ros](https://github.com/gramaziokohler/compas_fab/tree/master/src/compas_fab/backends/ros) to where these files are located? Perhaps that's also a  suitable place to mention the suggested cross-reference to this repo?

**Comment by gonzalocasas** [comment]
> that said, docs aren't a very orthodox location for docker-compose files...

hehe.. true dat!

I've moved them here to this repo and updated the readme.md here linking to the compose files, also added an example of the novnc showing rviz in the browser. I'll update the docs of compas_fab to link to these compose files soon-ish (maybe with a submodule, indeed).

**Comment by gonzalocasas** [comment]
I will close this one for now, since the docker-compose files have been moved here. But as usual, feel free to keep commenting on it, or open new issues if you feel like. :)
