### ISSUE TITLE
Better shell experience inside containers

### ISSUE THREAD

**Issue by tetov** [gramaziokohler/ros_docker#2]
I've added two lines to my forks Dockerfiles that makes life a lot easier it's necessary to run a shell inside one of the ros containers.

```bash
echo "set +e" >> /ros_entrypoint.sh \
&& echo "source /ros_entrypoint.sh" >> /root/.bashrc
```

It gets annoying to remember to source `/ros_entrypoint.sh` and what's even more annyoing is having shell exit whenever a command returns a non zero.

See example [here](https://github.com/tetov/ros_docker/blob/master/ros-abb-planner/Dockerfile#L41).

**Comment by gonzalocasas** [comment]
Closed by #3
