### ISSUE TITLE
Moveit Package for ABB CRB 15000

### ISSUE THREAD

**Issue by JulianTrummer** [gramaziokohler/ros_docker#6]
To connect our new ABB CRB 15000 to the RRC pipeline, it would be great to have a Moveit package for this robot.

**Comment by gonzalocasas** [comment]
https://github.com/gramaziokohler/abb_crb15000_5_95_moveit_config

**Comment by gonzalocasas** [comment]
I'm closing this as it is already supported in the latest ROS images, here's an example just in case:
https://github.com/gramaziokohler/ros_docker/blob/master/examples/abb-crb15000_5_95-demo/docker-compose.yml
